### PR TITLE
Italian mods

### PR DESCRIPTION
**Pull request by adamjakab**
The problem: platform lists both regions and provinces in "state/province" field which is really confusing.
In Italy, regions do exist, but they are never used in addresses. We normally use it as a pre-selection to narrow down the list of provinces, but with autocomplete fields it is unnecessary.

So this PR tries to correct this by removing them completely.

Other small region changes:
  - 'Monza e Brianza' is really called: 'Monza e della Brianza'
  - 'Macerata' had wrong key 'IT-SC' -> corrected to 'IT-MC'

### CODE REVIEW

**Comment by adamjakab** [comment]
The initial PR states how data should be. Obviously, it does not resolve, yet:
  - update 'oro_dictionary_region' table with corrected codes  (SC->MC)
  - update 'oro_address' table with corrected codes(SC->MC)
  - do "something" about existing addresses which refer to removed regions

I think we'll need a specific migration class for this to be done.

**Comment by zebimax** [comment]
Thank you for specifying this moment. It will be great if you provide migrations which will update 
records in 'oro_dictionary_region' and 
handle all existing addresses which refer to modified regions.  Please note that this migration should check all tables that refer to updated or removed regions in 'oro_dictionary_region' and properly update records in such tables(I think the solution for removed regions is set to null corresponding fields).

**Comment by DimaSoroka** [comment]
@adamjakab are you still interested in this PR?

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for about an hour for the submission to be processed.

**Comment by adamjakab** [comment]
Dear @DimaSoroka,

I have accepted the CLA but at this poin of time I cannot anymore follow this PR. Pls delete/archive.
To my greatest sorrow the company I work for has abandoned (for the time being) the development for oro platform.  I have seen the progress you have made since last year and every now and then I'll check back to see what is happening at Oro.

The actual change in plans in my company was based on a few considerations made at managerial level which I know of and I have a list of things that they were requiring which at this point of time Oro Platform is missing. (One of them was the personalization of the index view to be able to select and reorder table columns and to my great joy I saw it implemented in the last version I saw a few weeks back.) 

I'd be really happy to share this list with you beacuse your platform would greatly benefit from this (and so I could come back to develop for your platform instead of developing for some mouldy, php5.2 compatible spaghetti code CRM - no names!).

Pls, tell me how to comunicate this with your team.

Thanks for all your excellent work in the name of the open source comunity

a\

**Comment by sbani** [comment]
I would love to see the list too. Perhaps you can post it in the oro forum?

**Comment by artml** [comment]
Hi @adamjakab,

Please post the list of things we lack—it will definitely help us to set the correct priorities and make the platform better.

**Comment by DimaSoroka** [comment]
Closing this PR based on @adamjakab feedback. @adamjakab looking forward to have you as part of Oro community any time soon, feel free to share list of improvements you mentioned above as comment here or as a new issue. Thanks again!

**Pull request closed without merging**
