### PR TITLE
Extracted OroRequireJS bundle as standalone bundle

### LINKED ISSUE #100: Extract OroRequireJS bundle from OroCRM Platform
Hello, I saw the OroRequireJS bundle of the OroCRM Platform and it seems it's isn't too much CRM-specific. As I would use it in one of my own personal projects, my proposal is to extract it from the core of the platform and distribute it over packagist.org. What do you guys think? It would be great to have a public bundle that with a few config files is able to output a full RequireJS config.

### PR DESCRIPTION
**Pull request by ste93cry**
This should fix #100. Please review my changes before merging

### CODE REVIEW

**Comment by DimaSoroka** [comment]
Long time since last activity, @ste93cry are you still interested in this PR?

**Comment by ste93cry** [comment]
Yes I'm interested, although I don't need it anymore on the project I was working on at the moment of creating the issue. Anyway, the bundle was already released as standalone, but I don't know if it's really indipendent or if the only thing splitted was the repository.

**Comment by DimaSoroka** [comment]
It was only repository subtree split, we would be happy to assist with any maintenance effort if would like to test it and contribute necessary fixes.

**Comment by ste93cry** [comment]
My PR should still be valid, the only thing left to do is understand how to workaround the need of having the `oro_requirejs.cache` service registered in the `services.yml` file. That is a blocker issue for this feature.

**Comment by sergeyz** [comment]
Hi, @ste93cry !

You can add a compiler pass and check `oro.cache.abstract` exists. Replace it with `doctrine_cache.abstract.php_file` if not.

cc @vsoroka

**Comment by sergeyz** [comment]
Another option is to extract CacheBundle and add it as requirement to RequireJsBundle

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for about an hour for the submission to be processed.

**Comment by ste93cry** [comment]
@sergeyz Unfortunately some time go I deleted my fork without remembering about this PR. After recreating it I cannot obviously continue this PR, so I opened a new one: #496

**Comment by sergeyz** [comment]
@ste93cry you can always create a patch from PR https://patch-diff.githubusercontent.com/raw/orocrm/platform/pull/147.patch

**Comment by ste93cry** [comment]
The new PR uses a different approach to the problem and is ready for review

**Pull request closed without merging**
