### PR TITLE
[WIP] Symfony 3.0 upgrade 

### PR DESCRIPTION
**Pull request by umpirsky**
I am testing [Symfony Upgrade Fixer](https://github.com/umpirsky/Symfony-Upgrade-Fixer) against several Symfony projects.

Will continue pushing commits to this PR, I hope you will find them useful.

### CODE REVIEW

**Comment by DimaSoroka** [comment]
Thanks @umpirsky, we'll get to it later next year. Our next upgrade will be Symfony 2.8.

**Comment by umpirsky** [comment]
@DimaSoroka Sure, just testing the tool, thanks. ;)

**Comment by sagikazarmark** [comment]
@DimaSoroka For when is the 2.8 is scheduled? WIth the upcoming update #341 becomes invalid.

**Comment by DimaSoroka** [comment]
2.8 scheduled for Q1-Q2 next year

**Comment by sagikazarmark** [comment]
Do you think it' possible to merge the mentioned PR prior to that?

**Comment by DimaSoroka** [comment]
Yes, we'll include it in the release in January

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for about an hour for the submission to be processed.

**Comment by umpirsky** [comment]
@orocla Signed, thanks.

**Comment by Koc** [comment]
@umpirsky maybe this PR should be rebased and run tool again with disabling use reorder?

**Comment by umpirsky** [comment]
Yes, will do...

**Comment by mkudelya** [comment]
Hi @umpirsky 

We are planning migrate to Symfony3 at the end of this year after 3.4 release. Do you have any plans on this PR ?

**Comment by umpirsky** [comment]
@mkudelya We can close it, run [Symfony-Upgrade-Fixer](https://github.com/umpirsky/Symfony-Upgrade-Fixer) on latest code, and open new PR.

**Comment by mkudelya** [comment]
@umpirsky 

We will do that, thanks!

**Pull request closed without merging**
