### PR TITLE
Add PHP 7 Support

### PR DESCRIPTION
**Pull request by inssein**
Renamed class "True" with "TrueCompatible" and "False" with "FalseCompatible" using:

```
find . -type f -exec   sed -i 's/Condition\\False()/Condition\\FalseCompatible()/g' {} +
find . -type f -exec   sed -i 's/Condition\\True()/Condition\\TrueCompatible()/g' {} +
find . -type f -exec   sed -i 's/Condition\\False$/Condition\\FalseCompatible/g' {} +
find . -type f -exec   sed -i 's/Condition\\True$/Condition\\TrueCompatible/g' {} +
mv src/Oro/Component/ConfigExpression/Condition/True.php src/Oro/Component/ConfigExpression/Condition/TrueCompatible.php
mv src/Oro/Component/ConfigExpression/Condition/False.php src/Oro/Component/ConfigExpression/Condition/FalseCompatible.php
sed -i 's/class True/class TrueCompatible/g' src/Oro/Component/ConfigExpression/Condition/TrueCompatible.php
sed -i 's/class False/class FalseCompatible/g' src/Oro/Component/ConfigExpression/Condition/FalseCompatible.php
```

The above commands were from markus in http://www.orocrm.com/forums/topic/php-7-0-compatibility

### CODE REVIEW

**Comment by inssein** [comment]
Currently not tested. I am battling an odd issue:
```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "oro_email.listener.datagrid.context.contact" has a dependency on a non-existent parameter "oro_email.listener.datagrid.context.class". Did you mean one of these: "oro_email.helper.datagrid.emails.class", "oro_email.listener.datagrid.email.class", "oro_email.listener.datagrid.activity.class", "oro_email.listener.search_listener.class", "oro_email.listener.datagrid.mailbox_grid.class", "oro_activity.listener.datagrid.context.class", "orocrm_call.listener.datagrid.activity.class", "orocrm_task.listener.datagrid.activity.class"? in /www/crm/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:94
```

**Comment by sbani** [comment]
Thank you @inssein! Can you please add php7 to the travis-ci tests?
`
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
`
Then we know if it's working with php7.

**Comment by inssein** [comment]
@sbani done. I added hhvm as well like you requested, but it didn't seem to work with phpenv.

**Comment by sbani** [comment]
Okay... More difficult than I thought.

PHP7 fails during unit tests.
HHVM needs more config.
PHP5.* hits the memory limit.

Do you want to do it on your own or should I help you with that?
I could add hhvm in an extra repo and configure it. So you can concentrate on PHP7.

**Comment by DimaSoroka** [comment]
We are going to enable PHP7 support in the upcoming release in January

**Comment by sbani** [comment]
What do you mean with that?
Should we stop here because you do it and won't merge this one?
Should be go on but you will support us (or look at this) in January?

**Comment by DimaSoroka** [comment]
If you'll be able to complete this PR sometime soon and all tests will be passing we'll use it as base. As soon as team will start on planned task they will add additional info to this ticket.

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for about an hour for the submission to be processed.

**Comment by sagikazarmark** [comment]
Any news?

**Comment by DimaSoroka** [comment]
It is on the way, we expect to complete work in next two weeks if no other surprises will appear

**Comment by dextervip** [comment]
+1

**Comment by artml** [comment]
@sagikazarmark @dextervip the development of PHP7 support is completed and merged to master.

**Comment by woei66** [comment]
which version will include this patch?

**Comment by DimaSoroka** [comment]
PHP7 will be released in 1.10.0

**Comment by diglin** [comment]
Great to support PHP7. OroCRM is much more faster. Thanks

**Pull request closed without merging**
