### PR TITLE
Address fields display NULL when street field is empty

### LINKED ISSUE #614: Address fields display NULL when street field is empty
Hi, small bug when entering partial addresses.

I should be able to submit a PR soon

image

### PR DESCRIPTION
**Pull request by sadortun**
Fix #614

### CODE REVIEW

**Comment by sadortun** [comment]
# Before 
image



# After
image

**Comment by sadortun** [comment]
This also fixes the Google map display

image

image

**Comment by mkudelya** [comment]
Hi @sadortun 

Thank you very much!

**Comment by sadortun** [comment]
Could also help #381

**Pull request closed without merging**
