### PR TITLE
Small clearing code

### PR DESCRIPTION
**Pull request by miracle84**

### CODE REVIEW

**Comment by miracle84** [comment]
CI error log:

Loading composer repositories with package information
Updating dependencies (including require-dev)
  [UnexpectedValueException]                                            
  Could not parse version constraint >=~2: Invalid version string "~2"

**Comment by mkudelya** [comment]
Hi @miracle84 

Would you please sign our Contributor License Agreement?

Thank you!

**Comment by mkudelya** [comment]
The temporary solution is to switch the plugin to the master branch.

`composer global require fxp/composer-asset-plugin:dev-master`

**Comment by miracle84** [comment]
1. I already signed Contributor License Agreement
2. About trouble - I just describe reason why CI checks failed(That trouble not in my pull request)

**Comment by mkudelya** [comment]
Your PR has been merged. Thank you! I'm closing this PR

**Pull request closed without merging**
