### PR TITLE
Fixed a small bug that was forcing the owner field of an entity to b…

### PR DESCRIPTION
**Pull request by ioantihon**
Fixed a small bug that was forcing the owner field of an entity to be named "owner". 
Bellow you can check my config

 ```
* @Config(
 *      defaultValues={
 *          "ownership"={
 *              "owner_type"="BUSINESS_UNIT",
 *              "owner_field_name"="businessUnitOwner",
 *              "owner_column_name"="businessunit_owner_id",
 *              "organization_field_name"="organization",
 *              "organization_column_name"="organization_id"
 *          },
 *          "security"={
 *              "type"="ACL",
 *              "group_name"=""
 *          }
 *      }
 * )
```

### CODE REVIEW

**Comment by sergeyz** [comment]
Hi, @ioantihon !

Thanks a lot for your contribution! Please checks lines 859 and 862 - looks like same issues. Are you able to fix them too?

**Comment by ioantihon** [comment]
Yes, I changed them. My fork was not synced and in the newer versions the lines 859 and 862 were modified

**Comment by hurricane-voronin** [comment]
Hi @ioantihon 

Thanks for your PR, soon you'll see it at master.

**Comment by iklymenko** [comment]
@ioantihon , changes are merged, thanks for your contribution!

**Pull request closed without merging**
