### PR TITLE
Update Sensio Distribution Bundle

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for about an hour for the submission to be processed.

**Comment by sagikazarmark** [comment]
@orocla Signed it.

**Comment by mbessolov** [comment]
Hi @sagikazarmark,

The orocla bot didn't receive your CLA signature submission. There is a submission with a similar username though. If it was you and it's just a typo in the username - please sign in the form again with the correct GitHub username specified. Sorry for any inconvenience.

Thank you for your contribution.

Best Regards,
Michael

**Comment by sagikazarmark** [comment]
@mbessolov @orocla Signed it again.

**Comment by iklymenko** [comment]
@sagikazarmark, thanks for your contribution. Your changes will be merged very soon.

**Comment by sagikazarmark** [comment]
Yupiiii.
Thanks. :smile:

**Pull request merged**
