### PR TITLE
Refactored AbstractAddress::__toString

### PR DESCRIPTION
**Pull request by sbani**
- Extended the unit tests for AbstractAddress::__toString()
- Enhanced readability for method
  - Removed strange str_replace
  - Removed strange $check

Results in faster method and clearer code.

Successor of #566 because rebased on master.

### CODE REVIEW

**Comment by mkudelya** [comment]
Thank you @sbani !

**Comment by sbani** [comment]
any updates here?

**Comment by mkudelya** [comment]
Hi @sbani 

I will be merging pull requests this week. Thank you for your patience!

**Comment by sbani** [comment]
thank you too @mkudelya

**Comment by mkudelya** [comment]
I have merged this PR to the master branch. Thank you!

**Pull request closed without merging**
