### PR TITLE
[MessageQueue] Compatibility with Symfony 3

### PR DESCRIPTION
**Pull request by tadcka**

### CODE REVIEW

**Comment by sadortun** [comment]
Hi @tadcka  Interesting, how smooth things are running under Symfony3 ?

**Comment by tadcka** [comment]
Hello, i want to use https://github.com/orocrm/OroMessageQueueBundle other project

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by mkudelya** [comment]
@tadcka 

I want to ask you, how did you test compatibility of this bundle with symfony 3 ?

**Comment by tadcka** [comment]
@mkudelya 
Testing with symfony-standard 3.2. Get exception on NumericNodeDefinition https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Definition/Builder/NumericNodeDefinition.php#L71 
I just trying use with symfony3. I dont want fork this bundle.

**Comment by mkudelya** [comment]
Hi @tadcka 

Could you please write script which we able to run on travis ? For example it will download symfony 3, put MessageQueue bundle to core and run php unit tests inside bundle. [Here](https://github.com/orocrm/platform/blob/master/.travis.yml) is an example similar script.

**Comment by tadcka** [comment]
@mkudelya  do you want enable travis on MessageQueueBundle repository?

**Comment by mbessolov** [comment]
@tadcka it would be better to enable testing of MessageQueueBundle with Symfony 3 within the current repository by adding necessary steps to .travis.yml because orocrm/OroMessageQueueBundle is a read-only repository.

**Comment by mkudelya** [comment]
Close pull request because it has no activity. Feel free open it if you have any question.

**Comment by aistis-** [comment]
Also waiting for v3 compatibility.

**Pull request closed without merging**
