### PR TITLE
Added xlsx (excel) datagrid export

### LINKED ISSUE #476: CSV Export Bug (Excel) with UTF-8 BOM and multiline Fields
Hi all,

exporting a datagrid to a csv (from a datagrid.yml grid or a report) leads to multiple errors in excel.
Excel is not very tolerant with csv, but nearly everyone who wants to export a csv opens it in excel.

Bug 1:
BOM is missing. That's why you see excel encoding errors.

Bug 2:
The newlines within a field are made with `\n\r`. This is not correct and should be `\n` only.

I start working no this **now** and will create a PR soon.

### PR DESCRIPTION
**Pull request by sbani**
It is now possible to export a datagrid (batch or not) as an xlsx (Excel 2007) file.
- Added tests
- Created base classes for the overlap between csv and xlsx.
- Added yaml configurations
- Added the `liuggio/ExcelBundle` for the excel service which is based on `phpoffice/phpexcel`
- Added the Bundle to the `OroImportExportBundle` bundles.yml because it's basically used there.

## TODO
- Create option to export "xls" instead of "xlsx".
- Create CSV with the same excel classes(?)

Closes #476

### CODE REVIEW

**Comment by mkudelya** [comment]
Hi @sbani ,
We have reviewed your pull request and have tested it. Export is working, but orocrm should work on 512MB memory limit. I created 10000 accounts and ran export, after 45 seconds i got fatal error:

Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 85 bytes) in /Library/WebServe
r/www/symfony/orocrmee_source/vendor/phpoffice/phpexcel/Classes/PHPExcel/CachedObjectStorage/CacheBase.php</b> on line 186

Please fix this issue

**Comment by sbani** [comment]
Thx @mkudelya for your tests. Found the bug (memory leak).

I basically removed the file write to the tmp file because it's not needed. I enrich the excel object step by step and write on `close()` to the file.

Though you have to know that the memory usage is always higher than writing CSV because there is no way to append data to the file (because it's zipped, etc).

But I tried it with around 12k accounts and it worked fine.

**Comment by mkudelya** [comment]
@sbani 
I can offer one decision, if grid contains more than 10k rows, before export orocrm will be show popup where you can choose, either cancel operation or continue at one's own risk. Similar popup exists on mass delete action.

**Comment by sbani** [comment]
sounds good. do I need to implement it? I prefer not to write frontend code if that's possible

**Comment by mkudelya** [comment]
@sbani we will do frontend on our side. thanks!

**Comment by sbani** [comment]
thank you

**Comment by artml** [comment]
Closing the PR as we've added missing functionality and merged it to master. @sbani thanks again for your contribution!

**Pull request closed without merging**
