### PR TITLE
[1.8] Fixed data migration bugs in address type/country

### PR DESCRIPTION
**Pull request by sbani**
Issue: #390
Cherry picked: 459e826 from #369
See #369 for detailed info

### CODE REVIEW

**Comment by alex-n-2k7** [comment]
Hi @sbani , Thanks for the contribution.  Merged.

**Comment by sbani** [comment]
When do you plan to release the bug fix? If you release it with 1.9 it's useless for me because everything's **broken now**

**Comment by DimaSoroka** [comment]
We are going to have release on Monday.

**Comment by sbani** [comment]
Thanks!

**Comment by sbani** [comment]
Do you still plan to release the 1.8.3?
I think a bug, which will not allow users to install or update Oro is a bigger one and shouldn't be shunted to a later time.
I mean till yesterday 1.8 was the official stable version and the bug was reported by myself 28 days ago. This means there was no bug fix of a known bug in stable version for 28 days although I created a PR directly.

**Comment by DimaSoroka** [comment]
@sbani, we are not going to release 1.8.3 community version as 1.9.0 already released and includes this bug fix, we do bug fix releases for enterprise edition only. 
All bug fix contribution to maintenance brunches could be used by changing version dependency to "version-dev" (1.8.x-dev in this case). We'll update our [contribution guide](http://www.orocrm.com/documentation/index/current/community/code) shortly to make this clear.

**Pull request merged**
