### PR TITLE
Widget grid configuration

### PR DESCRIPTION
**Pull request by ishakuta**
- allow to pass widget configuration params into grid widget

### CODE REVIEW

**Comment by ishakuta** [comment]
please let me know if you'll find it useful, so I'll add docs and tests

**Comment by artml** [comment]
@ishakuta what is the perceived use case for this? Make grid widgets like "recent contacts" configurable?

**Comment by ishakuta** [comment]
@artml yes, right it's possible to change title, 
imagine this use case: user wants to configure some value to bind it to the datagrid parameter, something like date range for the "Opportunities By Lead Source" (chart) widget, but for the grid.

The problem here is that master branch contains [hardcoded empty params](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DashboardBundle/EventListener/WidgetConfigurationLoadListener.php#L42) array that blocks such use case.
Maybe there's another way to achieve that, but it looks like a bug to me, imho.

**Comment by hurricane-voronin** [comment]
Hi @ishakuta ,
>please let me know if you'll find it useful, so I'll add docs and tests

Will be great if you add it.

**Comment by hurricane-voronin** [comment]
Hi @ishakuta, 
Thank you for the PR.  It was merged to development repository, so you should see you commit in public repository soon. It will be great if you add docs/tests for it in the new PR.

**Pull request closed without merging**
