### PR TITLE
Bug while using Amazon S3 as attachments backend

### PR DESCRIPTION
**Pull request by jordi-adame**

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by jordi-adame** [comment]
I just signed the CLA

**Comment by mkudelya** [comment]
Hi, @jordi-adame 

Thank you for your pull request. Oro developers have already been applied fix. It will be available soon.

**Comment by StephenOTT** [comment]
@mkudelya What is the status of this?

**Comment by mkudelya** [comment]
Hi @StephenOTT 

Since 1.10 version this pull request available. [Check it]( https://github.com/orocrm/platform/blob/1.10/src/Oro/Bundle/AttachmentBundle/Resources/views/Twig/file.html.twig#L4)

**Comment by mkudelya** [comment]
This pull request must be closed

**Pull request closed without merging**
